### PR TITLE
Update info for Winter 2017 workshop

### PR DESCRIPTION
**Pull request by melissacarbone**

### CODE REVIEW

**Comment by qiheme** [comment]
@melissacarbone we should look into building a small CMS so that we don't have to put in a PR each time to change the dates...but it looks good to me.

**Comment by qiheme** [comment]
Actually @melissacarbone do you know what the `app/views/home/._modal.html.haml.swp` file is? If not, we should probably remove it.

**Comment by melissacarbone** [comment]
thanks @qiheme !  Good catch, I didn't mean to commit the swp file.  I'm assuming we're ok with the tests failing on master?  If so I will merge this.

**Comment by qiheme** [comment]
@melissacarbone not even sure when we added Travis to this...will have to investigate that later. Right now, this should be fine to merge.

**Comment by rachelober** [comment]
it was probably me, working on a new website and want to start including
all this stuff.


---
Rachel Ober
rachelober@gmail.com
rachelober.com
twitter.com/rachelober
linkedin.com/in/rachelober

**Pull request merged**
